# This is a basic workflow to help you get started with Actions

name: ec2

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  job1:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
           terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ap-south-1

      - name: terraform init
        run: |
          cd module
          terraform init -reconfigure

      - name: terraform plan
        run: |
            cd module
            terraform plan
